import {createClient} from '@supabase/supabase-js';
import {privateFetch} from './private-fetch';
export const SESSION_LOST_EVENT='ffmc:session-lost';
const url=import.meta.env.VITE_SUPABASE_URL?.trim();
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
export const configured=Boolean(url?.startsWith('https://')&&key&&!url.includes('YOUR_PROJECT')&&!key.includes('REPLACE_ME'));
export const supabase=configured?createClient(url!,key!,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true},global:{fetch:privateFetch(url!,()=>window.dispatchEvent(new Event(SESSION_LOST_EVENT)))}}):null;
export type RecordItem={id?:string;kind:string;title:string;status:string;owner:string;due:string;notes:string;next:string;updated?:string};
export async function listRecords():Promise<RecordItem[]>{if(!supabase)throw Error('Connexion non configurée.');const {data,error}=await supabase.from('records').select('*').order('updated',{ascending:false});if(error)throw Error('Chargement impossible. Vérifiez votre accès ou réessayez.');return data.map(r=>({...r,due:r.due||''}));}
export async function saveRecord(record:RecordItem){if(!supabase)throw Error('Connexion non configurée.');const {id,updated,kind,title,status,owner,due,notes,next}=record;const payload={kind,title:title.trim(),status,owner,due:due||null,notes,next};if(!payload.title)throw Error('Le titre est obligatoire.');if(id){if(!updated)throw Error('Rechargez le dossier avant de le modifier.');const {data,error}=await supabase.from('records').update(payload).eq('id',id).eq('updated',updated).select('id').maybeSingle();if(error)throw Error('Enregistrement impossible. Votre saisie est conservée.');if(!data)throw Error('Ce dossier a été modifié par un autre membre ou votre accès a changé. Copiez votre saisie, puis rechargez la page.');}else{const {error}=await supabase.from('records').insert(payload);if(error)throw Error('Enregistrement impossible. Votre saisie est conservée.');}}

export type Publication={id?:string;title:string;body:string;published:boolean;created_at?:string;updated?:string};
export async function listPublications(onlyPublished=false):Promise<Publication[]>{if(!supabase)throw Error('Connexion non configurée.');let query=supabase.from('ca_publications').select('id,title,body,published,created_at,updated').order('created_at',{ascending:false});if(onlyPublished)query=query.eq('published',true);const {data,error}=await query;if(error)throw Error('Impossible de charger les mails partagés. Réessayez.');return data;}
export async function savePublication(p:Publication){if(!supabase)throw Error('Connexion non configurée.');const payload={title:p.title.trim(),body:p.body.trim(),published:p.published};if(!payload.title||!payload.body)throw Error('Complétez le titre et le message à partager.');if(p.id){if(!p.updated)throw Error('Rechargez la publication.');const {data,error}=await supabase.from('ca_publications').update(payload).eq('id',p.id).eq('updated',p.updated).select('id').maybeSingle();if(error)throw Error('Partage impossible. Vérifiez votre connexion et votre rôle.');if(!data)throw Error('La publication a changé. Rechargez la liste avant de réessayer.');}else{const {error}=await supabase.from('ca_publications').insert(payload);if(error)throw Error('Partage impossible. Votre saisie est conservée.');}}
