type Part={mimeType?:string;filename?:string;headers?:{name:string;value:string}[];body?:{data?:string};parts?:Part[]};
function decode(data:string,part:Part){const raw=Uint8Array.from(atob(data.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));const charset=part.headers?.find(h=>h.name.toLowerCase()==='content-type')?.value.match(/charset=["']?([^;\s"']+)/i)?.[1]||'utf-8';try{return new TextDecoder(charset).decode(raw);}catch{return new TextDecoder().decode(raw);}}
function htmlText(html:string){return html.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<\s*(br|\/p|\/div|\/li)\b[^>]*>/gi,'\n').replace(/<[^>]*>/g,'').replace(/&(?:amp|lt|gt|quot|apos|nbsp);/g,x=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&apos;':"'",'&nbsp;':' '}[x]||x)).replace(/&#(x[\da-f]+|\d+);/gi,(_,x)=>{const n=x[0].toLowerCase()==='x'?parseInt(x.slice(1),16):Number(x);return n>0&&n<=0x10ffff?String.fromCodePoint(n):'';});}
export function textFromPart(part:Part,depth=0):string{if(depth>12||part.filename)return '';if(part.mimeType==='multipart/alternative'){const plain=part.parts?.find(p=>p.mimeType==='text/plain');if(plain)return textFromPart(plain,depth+1);}if(part.parts?.length)return part.parts.map(p=>textFromPart(p,depth+1)).filter(Boolean).join('\n');if(!part.body?.data)return '';if(part.mimeType==='text/plain')return decode(part.body.data,part);if(part.mimeType==='text/html')return htmlText(decode(part.body.data,part));return '';}
export function normalizeMessage(message:any){if(!/^[a-f\d]+$/i.test(message.id)||!/^[a-f\d]+$/i.test(message.threadId))throw Error('Invalid Gmail ID');const headers=message.payload?.headers||[];const header=(name:string)=>String(headers.find((h:any)=>h.name.toLowerCase()===name)?.value||'');const text=textFromPart(message.payload||{})||String(message.snippet||'');return {is_newsletter:Boolean(header('list-id')||/newsletter|lettre d.information|\[rdp-ffmc\]|\[infos-reseau\]/i.test(header('subject'))||/newsletter@|lettres@information.dila.gouv.fr/i.test(header('from'))),id:message.id,thread_id:message.threadId,subject:(header('subject')||'(Sans objet)').slice(0,1000),sender:header('from').slice(0,1000),sent_at:new Date(Number(message.internalDate)).toISOString(),direction:message.labelIds?.includes('SENT')?'envoyé':'reçu',body:text.replaceAll('\u0000','').slice(0,30000),truncated:text.length>30000};}
export const topics=['CT moto','Manifestations','Balades','Réunions et CA','Partenaires','Administratif','Actualités générales','Politique et réglementation','Circulation et infrastructures','Sécurité routière','Formations et JTI','Relais Motards Calmos','Solidarité','Vie associative','Services et notifications','Autre'];
export const categories=['Actualités','Ordres du jour','Comptes rendus','Newsletters','Vie du réseau','Administratif','Notifications et publicité','Correspondance'];
export const priorities=['Courante','Importante','Urgente'];
export const actions=['À débattre','À répondre','À partager','Pour information'];
export const analysisSchema={type:'object',additionalProperties:false,properties:{category:{type:'string',enum:categories},topic:{type:'string',enum:topics},priority:{type:'string',enum:priorities},actions:{type:'array',items:{type:'string',enum:actions}},summary:{type:'string'},reason:{type:'string'},discussion:{type:'string'},reply_draft:{type:'string'},deadline:{type:['string','null']},uncertainties:{type:'string'}},required:['category','topic','priority','actions','summary','reason','discussion','reply_draft','deadline','uncertainties']};
export function validateAnalysis(a:any){if(!a||(a.category!==undefined&&!categories.includes(a.category))||!topics.includes(a.topic)||!priorities.includes(a.priority)||!Array.isArray(a.actions)||a.actions.length>4||a.actions.some((v:any)=>!actions.includes(v)))throw Error('Invalid analysis');for(const k of ['summary','reason','discussion','reply_draft','uncertainties'])if(typeof a[k]!=='string'||a[k].length>10000)throw Error('Invalid analysis');if(a.deadline!==null&&(typeof a.deadline!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(a.deadline)||Number.isNaN(Date.parse(a.deadline))||new Date(a.deadline).toISOString().slice(0,10)!==a.deadline))throw Error('Invalid deadline');return Object.fromEntries(Object.keys(analysisSchema.properties).filter(k=>a[k]!==undefined).map(k=>[k,a[k]]));}
