'use client';
import {useState,useEffect} from 'react';
import {LayoutDashboard,FolderOpen,CalendarDays,Mail,Users,Plus,ArrowUpRight,ShieldCheck,ChevronLeft,ChevronRight,Check,ClipboardList,Newspaper} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Toaster,toast} from 'sonner';
import {listRecords,saveRecord,type RecordItem,type Publication} from './lib/backend';
import SharedMail,{PublicationEditor} from './SharedMail';
import GmailConnection from './GmailConnection';
import GmailInbox from './GmailInbox';
import NewsBoard from './NewsBoard';
import MotoNews from './MotoNews';
const nav=[['Vue d’ensemble',LayoutDashboard],['Dossiers & actions',FolderOpen],['Réunions',Users],['Calendrier',CalendarDays],['Courrier privé',Mail],['News moto & politique',Newspaper],['Actualités',ClipboardList],['Partages au CA',Users]] as const;
const empty=(kind='Dossier'):RecordItem=>({kind,title:'',status:kind==='Mail'?'À trier':'À réfléchir',owner:'',due:'',notes:'',next:''});
const format=(d:string)=>d?new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'}):'Date à définir';
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Paris'});
const meetingNotes='1. Fonctionnement de l’antenne et disponibilités\n2. Référents par dossier et répartition de la charge\n3. Autonomie et décisions à soumettre au CA\n4. Évolution du CA et règles sur les objets FFMC\n5. CT moto et propositions de mobilisation\n6. Prochaines actions, RMC et besoins en bénévoles\n7. Communication et suivi des dossiers\n8. Tour de table\n9. Référents, prochaines étapes et échéances\n\nDÉCISIONS DU CA\nÀ compléter pendant la réunion.';
export default function Dashboard(){const [view,setView]=useState(()=>new URLSearchParams(location.search).has('news')?'News moto & politique':new URLSearchParams(location.search).has('gmail')?'Courrier privé':'Vue d’ensemble'),[rows,setRows]=useState<RecordItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[form,setForm]=useState<RecordItem|null>(null),[saving,setSaving]=useState(false),[publication,setPublication]=useState<Publication|null>(null),[sharesVersion,setSharesVersion]=useState(0),[filter,setFilter]=useState('Tous'),[month,setMonth]=useState(()=>new Date());
async function refresh(){setLoading(true);try{setRows(await listRecords());setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{refresh();},[]);
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx)return;const abort=new AbortController();try{Promise.resolve(ctx.registerTool({name:'start_record_creation',description:'Ouvre le formulaire de création d’un dossier, d’une réunion ou d’un mail sans enregistrer.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['Dossier','Réunion','Mail']}},required:['kind'],additionalProperties:false},execute:async(input:any)=>{if(!['Dossier','Réunion','Mail'].includes(input?.kind))throw Error('Type invalide');setForm(empty(input.kind));return {opened:true,kind:input.kind};}},{signal:abort.signal})).catch(()=>{});}catch{}return()=>abort.abort();},[]);
const dossiers=rows.filter(r=>r.kind==='Dossier'),active=dossiers.filter(r=>r.status!=='Terminé'&&r.status!=='Archivé'),due=rows.filter(r=>r.due&&r.status!=='Terminé'&&r.status!=='Archivé').sort((a,b)=>a.due.localeCompare(b.due)),decisions=dossiers.filter(r=>r.status==='À décider');
function edit(kind='Dossier'){setForm(empty(kind));}
async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{await saveRecord(form!);setForm(null);toast.success('Enregistré');await refresh();}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}
function exportSummary(){const mails=rows.filter(r=>r.kind==='Mail'&&r.status==='À partager');const content='FFMC 06 — Synthèse à relire avant diffusion\n\n'+mails.map(r=>r.title+'\n'+r.notes+'\nSuite : '+r.next).join('\n\n');const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='FFMC06-synthese-CA.txt';a.click();URL.revokeObjectURL(url);}
const card=(r:RecordItem)=><button key={r.id} className="record" onClick={()=>setForm({...r})}><div className="record-top"><span className={'badge status-'+r.status.replaceAll(' ','-')}>{r.status}</span><ArrowUpRight size={17}/></div><h3>{r.title}</h3><p>{r.next||'Prochaine étape à préciser'}</p><div className="record-bottom"><span>{r.owner||'Référent à désigner'}</span><span className={r.due&&r.due<today()&&r.status!=='Terminé'?'overdue':''}>{format(r.due)}</span></div></button>;
const list=(items:RecordItem[],kind:string)=>items.length?<div className="cards">{items.map(card)}</div>:<div className="empty"><FolderOpen size={30}/><h3>Aucun {kind==='Mail'?'mail':kind==='Réunion'?'compte rendu':'dossier'} pour le moment</h3><p>{kind==='Dossier'?'Commencez par le CT moto ou une prochaine action.':'Ajoutez les informations utiles pour le CA.'}</p><button className="secondary" onClick={()=>edit(kind)}>Ajouter {kind==='Réunion'?'une réunion':kind==='Mail'?'un mail':'un dossier'}</button></div>;
return <SidebarProvider><Sidebar className="side" collapsible="offcanvas"><SidebarHeader><div className="brand"><span>06</span><div>FFMC<strong>ESPACE CA</strong></div></div></SidebarHeader><SidebarContent><p className="nav-label">FAIRE AVANCER L’ANTENNE</p><SidebarMenu>{nav.map(([n,Icon])=><SidebarMenuItem key={n}><SidebarMenuButton isActive={view===n} onClick={()=>{setView(n);setFilter('Tous')}}><Icon/><span>{n}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="sidebar-note"><ShieldCheck size={18}/><div>Espace privé<span>Conseil d’administration</span></div></div><div className="signature">Fédération française des<br/>motards en colère · Alpes-Maritimes</div></SidebarFooter></Sidebar><main className="workspace"><header className="topbar"><div><SidebarTrigger/><span>FFMC 06 <span className="slash">/</span> Vue coordinateur</span></div><span className="private"><ShieldCheck size={14}/> Privé</span></header><div className="page"><div className="page-title"><div><p className="eyebrow">LE COLLECTIF EN ACTION</p><h1>{view}</h1><p className="subtitle">{view==='News moto & politique'?'Les informations qui comptent pour les motards et leurs représentants.':view==='Vue d’ensemble'?'Les sujets à faire avancer, ensemble.':view==='Dossiers & actions'?'Une idée, un référent, une prochaine étape.':view==='Réunions'?'Préparer les échanges et garder une trace des décisions.':view==='Calendrier'?'Les dates des réunions et les échéances de vos dossiers.':'Trier les informations et préparer leur partage au CA.'}</p></div>{view!=='Partages au CA'&&view!=='Actualités'&&view!=='News moto & politique'&&<button className="primary" onClick={()=>edit(view==='Réunions'?'Réunion':view==='Courrier privé'?'Mail':'Dossier')}><Plus size={18}/>{view==='Réunions'?'Nouvelle réunion':view==='Courrier privé'?'Ajouter un mail':'Nouveau dossier'}</button>}</div>
{error&&<div role="alert" className="notice">{error} <button onClick={refresh}>Réessayer</button></div>}
{loading?<div className="empty">Chargement des dossiers…</div>:<>
{view==='Vue d’ensemble'&&<><div className="metrics">{[[active.length,'Dossiers en cours',FolderOpen,'Dossiers & actions'],[decisions.length,'Points à décider',ClipboardList,'Dossiers & actions'],[due.filter(r=>r.due>=today()&&r.due<=new Date(Date.now()+7*86400000).toLocaleDateString('sv-SE')).length,'Échéances sous 7 jours',CalendarDays,'Calendrier'],[rows.filter(r=>r.kind==='Mail'&&r.status==='À trier').length,'Mails à trier',Mail,'Courrier privé']].map(([count,label,Icon,target]:any)=><button className="metric" key={label} onClick={()=>{setView(target);if(label==='Points à décider')setFilter('À décider')}}><Icon size={21}/><strong>{count}</strong><span>{label}</span></button>)}</div><div className="overview"><section><div className="section-head"><h2>À l’ordre du jour</h2><span>{decisions.length} à décider</span></div>{decisions.length?list(decisions,'Dossier'):<div className="meeting-prompt"><div className="square-icon"><Users size={24}/></div><p className="eyebrow">PROCHAINE RÉUNION DU CA</p><h2>Mieux répartir.<br/>Faire avancer les actions.</h2><p>Un ordre du jour prêt à adapter : organisation, référents, CT moto et prochaines mobilisations.</p><button className="secondary" onClick={()=>setForm({...empty('Réunion'),title:'CA — Organisation et prochaines actions',notes:meetingNotes})}>Préparer cette réunion <ArrowUpRight size={16}/></button></div>}<div className="section-head"><h2>Dossiers à suivre</h2><button className="text-btn" onClick={()=>setView('Dossiers & actions')}>Tout voir <ArrowUpRight size={15}/></button></div>{list(active.slice(0,4),'Dossier')}</section><aside className="agenda"><div className="section-head"><h2>À venir</h2><CalendarDays size={19}/></div>{due.length?due.slice(0,6).map(r=><button className="agenda-item" key={r.id} onClick={()=>setForm({...r})}><strong>{format(r.due)}</strong><span>{r.title}<small>{r.owner||'Référent à désigner'}</small></span></button>):<p className="muted">Aucune échéance fixée.<br/>Les dates ajoutées aux dossiers et réunions apparaîtront ici.</p>}<button className="text-btn" onClick={()=>setView('Calendrier')}>Ouvrir le calendrier <ArrowUpRight size={15}/></button><div className="principle"><span>NOTRE FONCTIONNEMENT</span><h3>Chacun peut porter<br/>une proposition.</h3><p>On propose, on échange, on décide ensemble. Puis un référent fait avancer le sujet.</p></div></aside></div></>}
{view==='Dossiers & actions'&&<><div className="filters">{['Tous','À réfléchir','À décider','En cours','Terminé'].map(s=><button className={filter===s?'chosen':''} key={s} onClick={()=>setFilter(s)}>{s}</button>)}</div>{list(dossiers.filter(r=>filter==='Tous'||r.status===filter),'Dossier')}</>}
{view==='Réunions'&&<><div className="notice"><span>Gagnez du temps avec l’ordre du jour préparé pour votre point d’organisation.</span><button onClick={()=>setForm({...empty('Réunion'),title:'CA — Organisation et prochaines actions',notes:meetingNotes})}>Utiliser le modèle</button></div>{list(rows.filter(r=>r.kind==='Réunion'),'Réunion')}</>}
{view==='Courrier privé'&&<><GmailConnection/><GmailInbox onPrepareShare={setPublication} onPrepareRecord={setForm}/><h2>Courrier ajouté manuellement</h2><div className="section-head"><div className="filters">{['Tous','À trier','À partager','Archivé'].map(s=><button key={s} className={filter===s?'chosen':''} onClick={()=>setFilter(s)}>{s}</button>)}</div><button className="secondary" disabled={!rows.some(r=>r.kind==='Mail'&&r.status==='À partager')} onClick={exportSummary}>Exporter la synthèse à relire</button></div>{list(rows.filter(r=>r.kind==='Mail'&&(filter==='Tous'||r.status===filter)),'Mail')}</>}
{view==='News moto & politique'&&<MotoNews onPrepareShare={setPublication} onPrepareRecord={setForm}/>}
{view==='Actualités'&&<NewsBoard onPrepareShare={setPublication} onPrepareRecord={setForm}/>}
{view==='Partages au CA'&&<SharedMail manage refreshKey={sharesVersion}/>}
{view==='Calendrier'&&<><div className="calendar"><div className="section-head"><h2>{month.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</h2><div className="calendar-controls"><button aria-label="Mois précédent" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><button onClick={()=>setMonth(new Date())}>Aujourd’hui</button><button aria-label="Mois suivant" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div></div><div className="calendar-grid">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(d=><div className="dayname" key={d}>{d}</div>)}{Array.from({length:(new Date(month.getFullYear(),month.getMonth(),1).getDay()+6)%7},(_,i)=><div className="day blank" key={'blank'+i}/>)}{Array.from({length:new Date(month.getFullYear(),month.getMonth()+1,0).getDate()},(_,i)=>{const date=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return <div className={'day '+(date===today()?'today':'')} key={date}><span>{i+1}</span>{rows.filter(r=>r.due===date).map(r=><button key={r.id} onClick={()=>setForm({...r})}>{r.title}</button>)}</div>})}</div></div><h2 className="below">Échéances à suivre</h2>{due.length?list(due,'Dossier'):<p className="muted">Ajoutez une date à un dossier ou à une réunion pour le retrouver ici.</p>}</>}
</>}</div><footer>FFMC 06 <span>·</span> Espace de travail du conseil d’administration</footer></main>
<Dialog open={!!form&&!publication} onOpenChange={v=>{if(!v&&!saving)setForm(null)}}><DialogContent className="editor"><DialogHeader><DialogTitle>{form?.id?'Modifier':'Ajouter'} {form?.kind==='Réunion'?'une réunion':form?.kind==='Mail'?'un mail':'un dossier'}</DialogTitle><DialogDescription>{form?.kind==='Mail'?'Conservez les éléments utiles, puis préparez leur diffusion.':'Précisez qui fait avancer le sujet et la prochaine étape.'}</DialogDescription></DialogHeader>{form&&<form onSubmit={save}><label>Titre<input required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-row"><label>Statut<Select value={form.status} onValueChange={v=>setForm({...form,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{(form.kind==='Mail'?['À trier','À partager','Archivé']:['À réfléchir','À décider','En cours','Terminé']).map(s=><SelectItem value={s} key={s}>{s}</SelectItem>)}</SelectContent></Select></label><label>{form.kind==='Réunion'?'Date de réunion':'Échéance'}<input type="date" value={form.due} onChange={e=>setForm({...form,due:e.target.value})}/></label></div><label>{form.kind==='Mail'?'Expéditeur / suivi par':'Référent / équipe'}<input value={form.owner} maxLength={200} placeholder="Nom de la personne ou des volontaires" onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>{form.kind==='Réunion'?'Ordre du jour, points importants et décisions':form.kind==='Mail'?'Mail, réponses reçues et notes privées':'Informations et propositions'}<textarea rows={7} maxLength={30000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label>Prochaine étape<textarea rows={2} maxLength={30000} value={form.next} placeholder="Quelle action concrète doit suivre ?" onChange={e=>setForm({...form,next:e.target.value})}/></label><div className="form-actions">{form.kind==='Mail'&&<button type="button" className="secondary" disabled={saving} onClick={()=>{setPublication({title:form.title,body:'',published:true});}}>Préparer un partage au CA</button>}<button type="button" className="secondary" disabled={saving} onClick={()=>setForm(null)}>Annuler</button><button className="primary" disabled={saving}><Check size={17}/>{saving?'Enregistrement…':'Enregistrer'}</button></div></form>}</DialogContent></Dialog>{publication&&<PublicationEditor initial={publication} onClose={()=>setPublication(null)} onSaved={()=>{setSharesVersion(v=>v+1);}}/>}<Toaster richColors position="bottom-right"/></SidebarProvider>;
}
