import {useEffect,useState} from 'react';
import {supabase} from './lib/backend';
type Status={configured:boolean;connected:boolean;mailbox:string};
const callbackMessages:Record<string,string>={cancelled:'Autorisation Google annulée.',failed:'La connexion Gmail a échoué. Réessayez.', 'not-configured':'La configuration Google doit être terminée.', 'consent-required':'Autorisez la lecture Gmail pour terminer la connexion.', 'wrong-account':'Choisissez la boîte coordinateur.ffmc06@gmail.com dans Google.'};
export default function GmailConnection(){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;const url=new URL(location.href);const callback=url.searchParams.get('gmail');if(callback){if(callbackMessages[callback])setError(callbackMessages[callback]);url.searchParams.delete('gmail');history.replaceState(null,'',url.pathname+url.search+url.hash);}void supabase!.functions.invoke('gmail-connect',{body:{action:'status'}}).then(({data,error})=>{if(!active)return;if(error)setError('Impossible de vérifier la connexion Gmail. Rechargez la page pour réessayer.');else setStatus(data);});return()=>{active=false;};},[]);
 async function connect(){setBusy(true);setError('');try{const {data,error}=await supabase!.functions.invoke('gmail-connect',{body:{action:'start'}});if(error||!data?.url)throw Error('Connexion impossible. Vérifiez le secret Google dans Supabase et réessayez.');const url=new URL(data.url);if(url.origin!=='https://accounts.google.com')throw Error('Adresse Google invalide.');location.assign(url.href);}catch(e){setError((e as Error).message);setBusy(false);}}
 return <div className="notice"><div><strong>Gmail · coordinateur.ffmc06@gmail.com</strong><p>{!status?'Vérification de la connexion…':status.connected?'Connexion Gmail enregistrée. Utilisez l’import ci-dessous pour récupérer les échanges.':status.configured?'Connectez la boîte du coordinateur pour préparer la lecture des messages.':'Configuration en attente : le secret client Google doit être enregistré dans Supabase.'}</p><p>Les mails saisis ci-dessous et leurs réponses restent privés. Le statut « À partager » ne publie rien au CA.</p>{error&&<p role="alert" className="overdue">{error}</p>}</div>{status?.configured&&<button className="secondary" disabled={busy} onClick={connect}>{busy?'Ouverture de Google…':status.connected?'Reconnecter Gmail':'Connecter Gmail'}</button>}</div>;
}
