import {useEffect,useState} from 'react';
import {Mail,RefreshCw,Users,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {listPublications,savePublication,type Publication} from './lib/backend';
import {toast,Toaster} from 'sonner';
export function PublicationEditor({initial,onClose,onSaved}:{initial:Publication;onClose:()=>void;onSaved:()=>void}){
 const [form,setForm]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await savePublication({...form,published:true});toast.success('Le mail est maintenant visible par les membres du CA.');onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="editor"><DialogHeader><DialogTitle>{initial.id?'Modifier le mail partagé':'Partager un mail au CA'}</DialogTitle><DialogDescription>Seuls le titre et le texte ci-dessous seront visibles par tous les membres autorisés. Aucun email externe n’est envoyé.</DialogDescription></DialogHeader><form onSubmit={submit}><label>Titre visible par le CA<input required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Message à partager<textarea required rows={12} maxLength={30000} value={form.body} placeholder="Collez le mail ou rédigez la synthèse que les membres doivent lire." onChange={e=>setForm({...form,body:e.target.value})}/></label>{error&&<p role="alert" className="overdue">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Annuler</button><button className="primary" disabled={busy}>{busy?'Publication…':'Publier dans l’espace CA'}</button></div></form></DialogContent></Dialog>;
}
export default function SharedMail({manage=false,refreshKey=0}:{manage?:boolean;refreshKey?:number}){
 const [items,setItems]=useState<Publication[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState<Publication|null>(null),[busy,setBusy]=useState<string|null>(null);
 async function refresh(){setLoading(true);try{setItems(await listPublications(!manage));setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>{void refresh();},60000);return()=>window.clearInterval(timer);},[manage,refreshKey]);
 async function withdraw(p:Publication){setBusy(p.id!);try{await savePublication({...p,published:false});toast.success('Le mail a été retiré de l’espace CA.');await refresh();}catch(e){toast.error((e as Error).message);}finally{setBusy(null);}}
 return <section className={manage?'shared-section':'member-page'}>{!manage&&<div className="member-brand"><span>06</span><strong>FFMC · Espace CA</strong></div>}<div className="page-title"><div><p className="eyebrow">{manage?'DIFFUSION INTERNE':'INFORMATIONS DU COORDINATEUR'}</p><h1>{manage?'Mails partagés au CA':'Les mails partagés avec vous'}</h1><p className="subtitle">{manage?'Relisez, publiez et retirez les informations visibles par le CA.':'Les informations sélectionnées par le coordinateur, réunies au même endroit.'}</p></div><div className="sharing-actions"><button className="secondary" disabled={loading} onClick={refresh}><RefreshCw size={16}/> Actualiser</button>{manage&&<button className="primary" onClick={()=>setEditor({title:'',body:'',published:true})}><Plus size={17}/> Nouveau partage</button>}</div></div>{error&&<p role="alert" className="notice">{error}</p>}{loading&&!items.length?<p className="muted">Chargement des mails…</p>:!items.length?<div className="empty"><Mail size={30}/><h3>Aucun mail partagé pour le moment</h3><p>{manage?'Publiez un premier message ou préparez un partage depuis votre courrier privé.':'Les mails publiés par le coordinateur apparaîtront ici.'}</p></div>:<div className="publications">{items.map(p=><article key={p.id} className="publication"><div className="publication-meta"><span><Users size={15}/> Coordinateur FFMC 06</span><span>{p.published?'Visible par le CA':'Partage retiré'} · {p.created_at?new Date(p.created_at).toLocaleDateString('fr-FR'):''}</span></div><h2>{p.title}</h2><div className="publication-body">{p.body}</div>{manage&&<div className="sharing-actions"><button className="secondary" onClick={()=>setEditor({...p})}>{p.published?'Modifier le partage':'Republier'}</button>{p.published&&<button className="secondary" disabled={busy===p.id} onClick={()=>withdraw(p)}>{busy===p.id?'Retrait…':'Retirer du CA'}</button>}</div>}</article>)}</div>}{editor&&<PublicationEditor initial={editor} onClose={()=>setEditor(null)} onSaved={refresh}/>}<Toaster richColors position="bottom-right"/></section>;
}
